from handlers.commands.start import *
from handlers.callbacks.start_callback import *
from handlers.commands.char import *
from handlers.callbacks.stats_callback import *
from handlers.commands.bal import *
from handlers.commands.inv import *
from handlers.commands.dice import *
from handlers.callbacks.dice_callback import *
from handlers.commands.pay import *
from handlers.commands.spin import *
from handlers.callbacks.spin_callback import *
from handlers.commands.mychar import *
from handlers.callbacks.mychar_callback import *
from handlers.callbacks.cancle_task import *
from handlers.commands.add import *
from handlers.commands.profile import *